Repository nphuonha2101/BookStore_Software-Engineering, pull requests merged in 2024-06, with the labels that each got.

#54 #45 - Completed search feature
  Bookstore/src/main/java/com/software/bookstore/http/controllers/api/SearchAPI.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/ProductsController.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/BaseRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/BookRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/services/BookService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/CartDetailService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/CartService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/CategoryService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/ForgotPasswordService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/IService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/PaymentService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/UserSerivce.java
  Bookstore/src/main/java/com/software/bookstore/utils/Pagination.java
  Bookstore/src/main/webapp/public/css/header.css
  Bookstore/src/main/webapp/public/css/products.css
  Bookstore/src/main/webapp/public/css/search-modal.css
  Bookstore/src/main/webapp/public/js/handleSearch.js
  Bookstore/src/main/webapp/public/js/header.js
  Bookstore/src/main/webapp/views/client/layouts/master.jsp
  Bookstore/src/main/webapp/views/client/pages/products.jsp
  Bookstore/src/main/webapp/views/client/partials/header.jsp
  Bookstore/src/main/webapp/views/client/partials/search-modal.jsp
Labels: feature

#57 #55 - Complete payment with VNPay
  Bookstore/pom.xml
  Bookstore/src/main/java/com/software/bookstore/http/controllers/action/VnpayPaymentController.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/HomeController.java
  Bookstore/src/main/java/com/software/bookstore/utils/Decrypt.java
  Bookstore/src/main/java/com/software/bookstore/vnpay/VNPay.java
  Bookstore/src/main/webapp/application.properties.examples
Labels: feature

#60 #59 - fix: update application.properties.examples
  Bookstore/src/main/webapp/application.properties.examples
Labels: fix

#68 #61 - fix: error when save or update book caused by category
  Bookstore/src/main/java/com/software/bookstore/http/controllers/auth/RegisterController.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/ProductsController.java
  Bookstore/src/main/java/com/software/bookstore/http/enums/EAccountRole.java
  Bookstore/src/main/java/com/software/bookstore/http/filters/AuthenticationAdminFilter.java
  Bookstore/src/main/java/com/software/bookstore/http/models/User.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/UserRepository.java
  Bookstore/src/main/resources/db/data-2024-06-03_17h16m.sql
Labels: fix

#69 Test/add unit test
  Bookstore/pom.xml
  Bookstore/src/main/java/com/software/bookstore/http/controllers/api/dataTable/BookDataTableAPI.java
  Bookstore/src/main/java/com/software/bookstore/utils/Pagination.java
  Bookstore/src/main/java/com/software/bookstore/vnpay/VNPay.java
  Bookstore/src/test/java/com/software/bookstore/utils/DatesTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/DecryptTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/FilesTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/FormDataTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/MailsTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/PagesTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/PaginationTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/SessionAlertTest.java
  Bookstore/src/test/java/com/software/bookstore/utils/StringsTest.java
Labels: system
