Repository nphuonha2101/BookStore_Software-Engineering, pull requests merged in 2024-05, with the labels that each got.

#15 Thêm header và responsive
  Bookstore/src/main/webapp/public/css/header.css
  Bookstore/src/main/webapp/public/css/variables.css
  Bookstore/src/main/webapp/public/imgs/logo/logo.svg
  Bookstore/src/main/webapp/public/js/header.js
  Bookstore/src/main/webapp/views/client/layouts/master.jsp
  Bookstore/src/main/webapp/views/client/partials/header.jsp
Labels: enhancement

#21 Fix issues #18
  Bookstore/src/main/webapp/public/css/footer.css
  Bookstore/src/main/webapp/views/client/partials/footer.jsp
Labels: fix

#27 #26 - feat: complete to add custom 404 page
  Bookstore/src/main/webapp/WEB-INF/web.xml
  Bookstore/src/main/webapp/views/errors/404.html
Labels: system

#28 #25 - Config Mail Feature Completed
  Bookstore/pom.xml
  Bookstore/src/main/java/com/software/bookstore/configs/Mail.java
  Bookstore/src/main/java/com/software/bookstore/mail/Mail.java
  Bookstore/src/main/webapp/application.properties.examples
Labels: feature, system

#29 Cấu hình Repository, Service, Json Response
  Bookstore/src/main/java/com/software/bookstore/core/listeners/ContextListener.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/api/UserAPI.java
  Bookstore/src/main/java/com/software/bookstore/http/models/User.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/BaseRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/UserRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/response/EResponseCode.java
  Bookstore/src/main/java/com/software/bookstore/http/response/JsonFactory.java
  Bookstore/src/main/java/com/software/bookstore/http/response/Model.java
  Bookstore/src/main/java/com/software/bookstore/http/services/IService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/UserSerivce.java
  Bookstore/src/main/java/com/software/bookstore/resources/JakartaEE8Resource.java
  Bookstore/src/main/java/com/software/bookstore/utils/Strings.java
Labels: feature, system

#35 #31 - feat: add home page
  Bookstore/src/main/java/com/software/bookstore/configs/MailConfig.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/HomeController.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/BookRepository.java
  Bookstore/src/main/java/com/software/bookstore/mail/Mail.java
  Bookstore/src/main/webapp/public/css/variables.css
  Bookstore/src/main/webapp/public/imgs/backgrounds/home-banner.png
  Bookstore/src/main/webapp/views/client/pages/home.jsp
  Bookstore/src/main/webapp/views/client/partials/footer.jsp
  Bookstore/src/main/webapp/views/client/partials/header.jsp
  Bookstore/src/test/java/com/software/bookstore/http/repositories/BookRepositoryTest.java
Labels: feature

#36 #34 - Create product detail page completed!
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/HomeController.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/ProductDetailController.java
  Bookstore/src/main/java/com/software/bookstore/http/services/BookService.java
  Bookstore/src/main/webapp/public/css/product-detail.css
  Bookstore/src/main/webapp/public/js/product-detail.js
  Bookstore/src/main/webapp/views/client/layouts/master.jsp
  Bookstore/src/main/webapp/views/client/pages/product-detail.jsp
  Bookstore/src/main/webapp/views/client/pages/products.jsp
Labels: feature

#39 Fix/38 fix route
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/HomeController.java
Labels: fix

#46 Tính năng thanh toán
  Bookstore/src/main/java/com/software/bookstore/http/controllers/action/CartController.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/action/CashPaymentController.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/action/VnpayPaymentController.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/CartPageController.java
  Bookstore/src/main/java/com/software/bookstore/http/enums/PaymentMethod.java
  Bookstore/src/main/java/com/software/bookstore/http/enums/PaymentStatus.java
  Bookstore/src/main/java/com/software/bookstore/http/models/Payment.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/PaymentRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/services/CartDetailService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/PaymentService.java
  Bookstore/src/main/resources/db/data.sql
  Bookstore/src/main/webapp/views/client/pages/cart.jsp
  Bookstore/src/main/webapp/views/client/pages/product-detail.jsp
  Bookstore/src/main/webapp/views/client/partials/header.jsp
Labels: feature

#49 #41 - Create basic CRUD for Book completed!
  Bookstore/pom.xml
  Bookstore/src/main/java/com/software/bookstore/core/base/page/AdminPage.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/api/dataTable/BookDataTableAPI.java
  Bookstore/src/main/java/com/software/bookstore/http/controllers/render/BookManagementController.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/BaseRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/response/JsonFactory.java
  Bookstore/src/main/java/com/software/bookstore/http/services/BookService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/CartDetailService.java
  Bookstore/src/main/java/com/software/bookstore/http/services/IService.java
  Bookstore/src/main/java/com/software/bookstore/utils/FormData.java
  Bookstore/src/main/webapp/public/js/book-management.js
  Bookstore/src/main/webapp/views/admin/pages/book-management.jsp
  Bookstore/src/main/webapp/views/client/layouts/master.jsp
  Bookstore/src/main/webapp/views/client/pages/product-detail.jsp
  Bookstore/src/main/webapp/views/client/pages/products.jsp
Labels: feature

#53 #53 - Fix add and edit book completed
  Bookstore/src/main/java/com/software/bookstore/http/controllers/api/dataTable/BookDataTableAPI.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/BookRepository.java
  Bookstore/src/main/java/com/software/bookstore/http/repositories/CategoryRepository.java
  Bookstore/src/main/webapp/public/js/book-management.js
  Bookstore/src/main/webapp/views/admin/pages/book-management.jsp
Labels: fix
